import type { MetadataRoute } from "next";
import { PUBLIC_SITE_URL } from "@/lib/seo";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api/",
          "/dashboard",
          "/dashboard/",
          "/account",
          "/account/",
          "/admin",
          "/admin/",
          "/messages",
          "/messages/",
          "/settings",
          "/settings/",
          "/documents",
          "/documents/",
          "/billing",
          "/billing/",
          "/profile",
          "/profile/",
          "/onboarding",
          "/onboarding/",
          "/verification",
          "/verification/",
          "/applications",
          "/applications/",
          "/placements",
          "/placements/",
          "/interests",
          "/interests/",
          "/community",
          "/community/",
          "/shortlist",
          "/shortlist/",
          "/matches",
          "/matches/",
          "/availability",
          "/availability/",
          "/household",
          "/household/",
          "/connect",
          "/connect/",
          "/store",
          "/store/",
          "/boost",
          "/boost/",
          "/coach",
          "/coach/",
          "/offline",
          "/offline/",
        ],
      },
    ],
    sitemap: `${PUBLIC_SITE_URL}/sitemap.xml`,
    host: PUBLIC_SITE_URL,
  };
}
